// Matches Salesforce's Nationality__c restricted picklist values exactly.
// Confirmed by direct testing:
// - Most countries are listed by demonym (e.g. 'Indian', 'Afghan') - the country
//   name itself ('India', 'Afghanistan') is rejected.
// - United Arab Emirates is the one exception: the picklist has 'United Arab
//   Emirates' (the country name) rather than 'Emirati' (the demonym), which is
//   rejected. Likely just an inconsistency in how the picklist was populated on
//   the Salesforce side, not a rule that generalizes to other countries.
export interface NationalityListEntry {
  country: string;
  nationality: string;
}

export const NATIONALITY_LIST: readonly NationalityListEntry[] = [
  { country: 'Afghanistan', nationality: 'Afghan' },
  { country: 'Åland Islands', nationality: 'Ålandish' },
  { country: 'Albania', nationality: 'Albanian' },
  { country: 'Algeria', nationality: 'Algerian' },
  { country: 'American Samoa', nationality: 'American Samoan' },
  { country: 'Andorra', nationality: 'Andorran' },
  { country: 'Angola', nationality: 'Angolan' },
  { country: 'Anguilla', nationality: 'Anguillian' },
  { country: 'Antarctica', nationality: 'Antarctican' },
  { country: 'Antigua and Barbuda', nationality: 'Antiguan, Barbudan' },
  { country: 'Argentina', nationality: 'Argentine' },
  { country: 'Armenia', nationality: 'Armenian' },
  { country: 'Aruba', nationality: 'Aruban' },
  { country: 'Australia', nationality: 'Australian' },
  { country: 'Austria', nationality: 'Austrian' },
  { country: 'Azerbaijan', nationality: 'Azerbaijani' },
  { country: 'Bahamas', nationality: 'Bahamian' },
  { country: 'Bahrain', nationality: 'Bahraini' },
  { country: 'Bangladesh', nationality: 'Bangladeshi' },
  { country: 'Barbados', nationality: 'Barbadian' },
  { country: 'Belarus', nationality: 'Belarusian' },
  { country: 'Belgium', nationality: 'Belgian' },
  { country: 'Belize', nationality: 'Belizean' },
  { country: 'Benin', nationality: 'Beninese' },
  { country: 'Bermuda', nationality: 'Bermudian' },
  { country: 'Bhutan', nationality: 'Bhutanese' },
  { country: 'Bolivia', nationality: 'Bolivian' },
  { country: 'Bosnia and Herzegovina', nationality: 'Bosnian, Herzegovinian' },
  { country: 'Botswana', nationality: 'Motswana' },
  { country: 'Brazil', nationality: 'Brazilian' },
  { country: 'British Indian Ocean Territory', nationality: 'Indian' },
  { country: 'British Virgin Islands', nationality: 'Virgin Islander' },
  { country: 'Brunei', nationality: 'Bruneian' },
  { country: 'Bulgaria', nationality: 'Bulgarian' },
  { country: 'Burkina Faso', nationality: 'Burkinabe' },
  { country: 'Burundi', nationality: 'Burundian' },
  { country: 'Cambodia', nationality: 'Cambodian' },
  { country: 'Cameroon', nationality: 'Cameroonian' },
  { country: 'Canada', nationality: 'Canadian' },
  { country: 'Cape Verde', nationality: 'Cape Verdian' },
  { country: 'Caribbean Netherlands', nationality: 'Dutch' },
  { country: 'Cayman Islands', nationality: 'Caymanian' },
  { country: 'Central African Republic', nationality: 'Central African' },
  { country: 'Chad', nationality: 'Chadian' },
  { country: 'Chile', nationality: 'Chilean' },
  { country: 'China', nationality: 'Chinese' },
  { country: 'Christmas Island', nationality: 'Christmas Islander' },
  { country: 'Cocos (Keeling) Islands', nationality: 'Cocos Islander' },
  { country: 'Colombia', nationality: 'Colombian' },
  { country: 'Comoros', nationality: 'Comoran' },
  { country: 'Cook Islands', nationality: 'Cook Islander' },
  { country: 'Costa Rica', nationality: 'Costa Rican' },
  { country: 'Croatia', nationality: 'Croatian' },
  { country: 'Cuba', nationality: 'Cuban' },
  { country: 'Curaçao', nationality: 'Curaçaoan' },
  { country: 'Cyprus', nationality: 'Cypriot' },
  { country: 'Czechia', nationality: 'Czech' },
  { country: 'Denmark', nationality: 'Danish' },
  { country: 'Djibouti', nationality: 'Djibouti' },
  { country: 'Dominica', nationality: 'Dominican' },
  { country: 'Dominican Republic', nationality: 'Dominican' },
  { country: 'DR Congo', nationality: 'Congolese' },
  { country: 'Ecuador', nationality: 'Ecuadorean' },
  { country: 'Egypt', nationality: 'Egyptian' },
  { country: 'El Salvador', nationality: 'Salvadoran' },
  { country: 'Equatorial Guinea', nationality: 'Equatorial Guinean' },
  { country: 'Eritrea', nationality: 'Eritrean' },
  { country: 'Estonia', nationality: 'Estonian' },
  { country: 'Eswatini', nationality: 'Swazi' },
  { country: 'Ethiopia', nationality: 'Ethiopian' },
  { country: 'Falkland Islands', nationality: 'Falkland Islander' },
  { country: 'Faroe Islands', nationality: 'Faroese' },
  { country: 'Fiji', nationality: 'Fijian' },
  { country: 'Finland', nationality: 'Finnish' },
  { country: 'France', nationality: 'French' },
  { country: 'French Guiana', nationality: 'Guianan' },
  { country: 'French Polynesia', nationality: 'French Polynesian' },
  { country: 'French Southern and Antarctic Lands', nationality: 'French' },
  { country: 'Gabon', nationality: 'Gabonese' },
  { country: 'Gambia', nationality: 'Gambian' },
  { country: 'Georgia', nationality: 'Georgian' },
  { country: 'Germany', nationality: 'German' },
  { country: 'Ghana', nationality: 'Ghanaian' },
  { country: 'Gibraltar', nationality: 'Gibraltar' },
  { country: 'Greece', nationality: 'Greek' },
  { country: 'Greenland', nationality: 'Greenlandic' },
  { country: 'Grenada', nationality: 'Grenadian' },
  { country: 'Guadeloupe', nationality: 'Guadeloupian' },
  { country: 'Guam', nationality: 'Guamanian' },
  { country: 'Guatemala', nationality: 'Guatemalan' },
  { country: 'Guernsey', nationality: 'Channel Islander' },
  { country: 'Guinea', nationality: 'Guinean' },
  { country: 'Guinea-Bissau', nationality: 'Guinea-Bissauan' },
  { country: 'Guyana', nationality: 'Guyanese' },
  { country: 'Haiti', nationality: 'Haitian' },
  {
    country: 'Heard Island and McDonald Islands',
    nationality: 'Heard and McDonald Islander',
  },
  { country: 'Honduras', nationality: 'Honduran' },
  { country: 'Hong Kong', nationality: 'Hong Konger' },
  { country: 'Hungary', nationality: 'Hungarian' },
  { country: 'Iceland', nationality: 'Icelander' },
  { country: 'India', nationality: 'Indian' },
  { country: 'Indonesia', nationality: 'Indonesian' },
  { country: 'Iran', nationality: 'Iranian' },
  { country: 'Iraq', nationality: 'Iraqi' },
  { country: 'Ireland', nationality: 'Irish' },
  { country: 'Isle of Man', nationality: 'Manx' },
  { country: 'Israel', nationality: 'Israeli' },
  { country: 'Italy', nationality: 'Italian' },
  { country: 'Ivory Coast', nationality: 'Ivorian' },
  { country: 'Jamaica', nationality: 'Jamaican' },
  { country: 'Japan', nationality: 'Japanese' },
  { country: 'Jersey', nationality: 'Channel Islander' },
  { country: 'Jordan', nationality: 'Jordanian' },
  { country: 'Kazakhstan', nationality: 'Kazakhstani' },
  { country: 'Kenya', nationality: 'Kenyan' },
  { country: 'Kiribati', nationality: 'I-Kiribati' },
  { country: 'Kosovo', nationality: 'Kosovar' },
  { country: 'Kuwait', nationality: 'Kuwaiti' },
  { country: 'Kyrgyzstan', nationality: 'Kirghiz' },
  { country: 'Laos', nationality: 'Laotian' },
  { country: 'Latvia', nationality: 'Latvian' },
  { country: 'Lebanon', nationality: 'Lebanese' },
  { country: 'Lesotho', nationality: 'Mosotho' },
  { country: 'Liberia', nationality: 'Liberian' },
  { country: 'Libya', nationality: 'Libyan' },
  { country: 'Liechtenstein', nationality: 'Liechtensteiner' },
  { country: 'Lithuania', nationality: 'Lithuanian' },
  { country: 'Luxembourg', nationality: 'Luxembourger' },
  { country: 'Macau', nationality: 'Macanese' },
  { country: 'Madagascar', nationality: 'Malagasy' },
  { country: 'Malawi', nationality: 'Malawian' },
  { country: 'Malaysia', nationality: 'Malaysian' },
  { country: 'Maldives', nationality: 'Maldivan' },
  { country: 'Mali', nationality: 'Malian' },
  { country: 'Malta', nationality: 'Maltese' },
  { country: 'Marshall Islands', nationality: 'Marshallese' },
  { country: 'Martinique', nationality: 'Martinican' },
  { country: 'Mauritania', nationality: 'Mauritanian' },
  { country: 'Mauritius', nationality: 'Mauritian' },
  { country: 'Mayotte', nationality: 'Mahoran' },
  { country: 'Mexico', nationality: 'Mexican' },
  { country: 'Micronesia', nationality: 'Micronesian' },
  { country: 'Moldova', nationality: 'Moldovan' },
  { country: 'Monaco', nationality: 'Monegasque' },
  { country: 'Mongolia', nationality: 'Mongolian' },
  { country: 'Montenegro', nationality: 'Montenegrin' },
  { country: 'Montserrat', nationality: 'Montserratian' },
  { country: 'Morocco', nationality: 'Moroccan' },
  { country: 'Mozambique', nationality: 'Mozambican' },
  { country: 'Myanmar', nationality: 'Burmese' },
  { country: 'Namibia', nationality: 'Namibian' },
  { country: 'Nauru', nationality: 'Nauruan' },
  { country: 'Nepal', nationality: 'Nepalese' },
  { country: 'Netherlands', nationality: 'Dutch' },
  { country: 'New Caledonia', nationality: 'New Caledonian' },
  { country: 'New Zealand', nationality: 'New Zealander' },
  { country: 'Nicaragua', nationality: 'Nicaraguan' },
  { country: 'Niger', nationality: 'Nigerien' },
  { country: 'Nigeria', nationality: 'Nigerian' },
  { country: 'Niue', nationality: 'Niuean' },
  { country: 'Norfolk Island', nationality: 'Norfolk Islander' },
  { country: 'North Korea', nationality: 'North Korean' },
  { country: 'North Macedonia', nationality: 'Macedonian' },
  { country: 'Northern Mariana Islands', nationality: 'American' },
  { country: 'Norway', nationality: 'Norwegian' },
  { country: 'Oman', nationality: 'Omani' },
  { country: 'Pakistan', nationality: 'Pakistani' },
  { country: 'Palau', nationality: 'Palauan' },
  { country: 'Palestine', nationality: 'Palestinian' },
  { country: 'Panama', nationality: 'Panamanian' },
  { country: 'Papua New Guinea', nationality: 'Papua New Guinean' },
  { country: 'Paraguay', nationality: 'Paraguayan' },
  { country: 'Peru', nationality: 'Peruvian' },
  { country: 'Philippines', nationality: 'Filipino' },
  { country: 'Pitcairn Islands', nationality: 'Pitcairn Islander' },
  { country: 'Poland', nationality: 'Polish' },
  { country: 'Portugal', nationality: 'Portuguese' },
  { country: 'Puerto Rico', nationality: 'Puerto Rican' },
  { country: 'Qatar', nationality: 'Qatari' },
  { country: 'Republic of the Congo', nationality: 'Congolese' },
  { country: 'Réunion', nationality: 'Réunionese' },
  { country: 'Romania', nationality: 'Romanian' },
  { country: 'Russia', nationality: 'Russian' },
  { country: 'Rwanda', nationality: 'Rwandan' },
  { country: 'Saint Barthélemy', nationality: 'Saint Barthélemy Islander' },
  {
    country: 'Saint Helena, Ascension and Tristan da Cunha',
    nationality: 'Saint Helenian',
  },
  { country: 'Saint Kitts and Nevis', nationality: 'Kittitian or Nevisian' },
  { country: 'Saint Lucia', nationality: 'Saint Lucian' },
  { country: 'Saint Martin', nationality: 'Saint Martin Islander' },
  {
    country: 'Saint Pierre and Miquelon',
    nationality: 'Saint-Pierrais, Miquelonnais',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    nationality: 'Saint Vincentian',
  },
  { country: 'Samoa', nationality: 'Samoan' },
  { country: 'San Marino', nationality: 'Sammarinese' },
  { country: 'São Tomé and Príncipe', nationality: 'Sao Tomean' },
  { country: 'Saudi Arabia', nationality: 'Saudi Arabian' },
  { country: 'Senegal', nationality: 'Senegalese' },
  { country: 'Serbia', nationality: 'Serbian' },
  { country: 'Seychelles', nationality: 'Seychellois' },
  { country: 'Sierra Leone', nationality: 'Sierra Leonean' },
  { country: 'Singapore', nationality: 'Singaporean' },
  { country: 'Sint Maarten', nationality: 'St. Maartener' },
  { country: 'Slovakia', nationality: 'Slovak' },
  { country: 'Slovenia', nationality: 'Slovene' },
  { country: 'Solomon Islands', nationality: 'Solomon Islander' },
  { country: 'Somalia', nationality: 'Somali' },
  { country: 'South Africa', nationality: 'South African' },
  {
    country: 'South Georgia',
    nationality: 'South Georgian South Sandwich Islander',
  },
  { country: 'South Korea', nationality: 'South Korean' },
  { country: 'South Sudan', nationality: 'South Sudanese' },
  { country: 'Spain', nationality: 'Spanish' },
  { country: 'Sri Lanka', nationality: 'Sri Lankan' },
  { country: 'Sudan', nationality: 'Sudanese' },
  { country: 'Suriname', nationality: 'Surinamer' },
  { country: 'Svalbard and Jan Mayen', nationality: 'Norwegian' },
  { country: 'Sweden', nationality: 'Swedish' },
  { country: 'Switzerland', nationality: 'Swiss' },
  { country: 'Syria', nationality: 'Syrian' },
  { country: 'Taiwan', nationality: 'Taiwanese' },
  { country: 'Tajikistan', nationality: 'Tadzhik' },
  { country: 'Tanzania', nationality: 'Tanzanian' },
  { country: 'Thailand', nationality: 'Thai' },
  { country: 'Timor-Leste', nationality: 'East Timorese' },
  { country: 'Togo', nationality: 'Togolese' },
  { country: 'Tokelau', nationality: 'Tokelauan' },
  { country: 'Tonga', nationality: 'Tongan' },
  { country: 'Trinidad and Tobago', nationality: 'Trinidadian' },
  { country: 'Tunisia', nationality: 'Tunisian' },
  { country: 'Turkey', nationality: 'Turkish' },
  { country: 'Turkmenistan', nationality: 'Turkmen' },
  {
    country: 'Turks and Caicos Islands',
    nationality: 'Turks and Caicos Islander',
  },
  { country: 'Tuvalu', nationality: 'Tuvaluan' },
  { country: 'Uganda', nationality: 'Ugandan' },
  { country: 'Ukraine', nationality: 'Ukrainian' },
  { country: 'UAE', nationality: 'UAE' },
  { country: 'United Kingdom', nationality: 'British' },
  { country: 'United States', nationality: 'American' },
  {
    country: 'United States Minor Outlying Islands',
    nationality: 'American Islander',
  },
  { country: 'United States Virgin Islands', nationality: 'Virgin Islander' },
  { country: 'Uruguay', nationality: 'Uruguayan' },
  { country: 'Uzbekistan', nationality: 'Uzbekistani' },
  { country: 'Vanuatu', nationality: 'Ni-Vanuatu' },
  { country: 'Vatican City', nationality: 'Vatican' },
  { country: 'Venezuela', nationality: 'Venezuelan' },
  { country: 'Vietnam', nationality: 'Vietnamese' },
  { country: 'Wallis and Futuna', nationality: 'Wallis and Futuna Islander' },
  { country: 'Western Sahara', nationality: 'Sahrawi' },
  { country: 'Yemen', nationality: 'Yemeni' },
  { country: 'Zambia', nationality: 'Zambian' },
  { country: 'Zimbabwe', nationality: 'Zimbabwean' },
];
