// Matches Salesforce's Nationality__c restricted picklist values exactly - the
// frontend select must submit one of these strings verbatim or Salesforce rejects
// the record (INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST).
export const NATIONALITY_LIST: readonly string[] = [
  'Afghan',
  'Aland Islands',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Antiguan and Barbudan',
  'Argentine',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahraini',
  'Bangladeshi',
  'Barbados',
  'Belarusian',
  'Belgian',
  'Bosnia and Herzegovina',
  'Brazilian',
  'British',
  'Bulgarian',
  'Burkinese',
  'Cameroonian',
  'Canadian',
  'Chadian',
  'Chinese',
  'Colombian',
  'Congolese',
  'Croatian',
  'Cypriot',
  'Cyprus',
  'Czech',
  'Czech Republic',
  'Danish',
  'Denmark',
  'Djiboutian',
  'Dominican',
  'Dutch',
  'Egyptian',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Filipino',
  'Finnish',
  'France',
  'French',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guinean',
  'Hungarian',
  'Indian',
  'Indonesian',
  'Irani',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kenyan',
  'Kittitian and Nevisian',
  'Korean',
  'Kuwaiti',
  'Kyrgyzstani',
  'Latvian',
  'Lebanese',
  'Lesotho',
  'Liberian',
  'Libyan',
  'Lithuanian',
  'Luxembourger',
  'Madagascan',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Mauritanian',
  'Mexican',
  'Moldavian',
  'Montenegrin',
  'Moroccan',
  'Motswana',
  'Namibian',
  'Nepali',
  'Netherlands',
  'New Zealander',
  'Nigerian',
  'Ni-Vanuatu',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Palestinian',
  'Paraguayan',
  'Peruvian',
  'Philippines',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Saint Lucian',
  'Saudi',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Sierra Leonian',
  'Singaporean',
  'Slovenian',
  'Somali',
  'South African',
  'Spain',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamese',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajikistan',
  'Tanzanian',
  'Thai',
  'Tunisian',
  'Turkish',
  'Turkmenistani',
  'UAE',
  'Ugandan',
  'Ukrainian',
  'United Kingdom',
  'Uzbekistani',
  'Venezuelan',
  'Welsh',
  'Yemeni',
  'Zambian',
  'Zimbabwean',
];
